Feat: Home menu backend integration
76eren/IPSEN5-frontend pull request #16
Opened 2024-05-24 12:34 UTC by StanSmits

<img width="819" alt="image" src="https://github.com/76eren/IPSEN5-frontend/assets/79027654/c6e05253-bd19-4ab2-9668-b67b709ae6cc">

Added integration with backend for upcoming 3 reservations

2024-05-24 13:15 UTC, isabelhb requested changes

2024-05-30 08:57 UTC, isabelhb approved these changes

2024-05-30 09:58 UTC, s1143282 requested changes

2024-05-30 09:58 UTC, s1143282 commented on src/app/home/upcoming-reservations/upcoming-reservations.component.ts
> -  @Input() reservations: Reservation[] = [];
Volgens mij is het netter om de data die je in de child components gebruikt in de parent component op te halen en dan via een input door te sturen dus eigenlijk hoe het eerst werd gedaan.

2024-05-30 09:58 UTC, s1143282 commented on src/app/home/upcoming-reservations/upcoming-reservations.component.ts
> +    let temp = await this.reservationService.getAllReservations();
Het is fijn als je deze inderdaad nog aanpast

2024-05-30 09:58 UTC, s1143282 commented on src/app/shared/service/reservation.service.ts
> +        console.error(error);
Dit graag ook nog toepassen met popup ofzo

2024-05-30 09:58 UTC, s1143282 commented on src/app/shared/service/reservation.service.ts
> +    return this.apiService.get<any>(`/reservations/${id}`)
Ik zou ipv any wel types gebruiken. We hebben in de apiservice een ApiResponse interface staan en dan kan je dit bijvoorbeeld gebruiken als ApiResponse<Reservation>

2024-05-30 09:58 UTC, s1143282 commented on src/app/shared/service/reservation.service.ts
> +        console.error(error);
ook hier zou ik popups voor userfeedback gebruiken

2024-06-01 09:57 UTC, s1143282 approved these changes

2024-06-01 09:58 UTC, merged