UNIFINISHED: Reservation details page
76eren/IPSEN5-frontend pull request #18
Opened 2024-05-27 12:42 UTC by StanSmits

2024-05-30 08:53 UTC, isabelhb requested changes

2024-05-30 08:53 UTC, isabelhb commented on src/app/app.routes.ts
>        // TODO add id of reservation in path
todo mag weg hier nu :)

2024-05-30 08:53 UTC, isabelhb commented on src/app/reservation-details/reservation-details.component.html
> +        alt="Location cover image"
bij alt ook fijn als er wordt aangegeven welke locatie er wordt getoond

2024-06-01 15:34 UTC, s1143282 approved these changes

2024-06-01 20:47 UTC, isabelhb approved these changes

2024-06-01 20:47 UTC, merged