All elements that are used on mobile view now are responsive on mobile
76eren/IPSEN5-frontend pull request #37
Opened 2024-06-12 13:36 UTC by StanSmits

Home view:

<img width="290" alt="image" src="https://github.com/76eren/IPSEN5-frontend/assets/79027654/44f0cccb-8af8-47ab-a603-c0c1935da999">

Favorites:
<img width="291" alt="image" src="https://github.com/76eren/IPSEN5-frontend/assets/79027654/4ea0af1d-4254-4283-a298-4ce2f11ef666">

Upcoming reservations:
<img width="296" alt="image" src="https://github.com/76eren/IPSEN5-frontend/assets/79027654/691bf3cc-6f1b-4fbc-a4e1-e34d7a009d5c">

kalender:
<img width="300" alt="image" src="https://github.com/76eren/IPSEN5-frontend/assets/79027654/b342ddac-c502-4930-800b-590f3d0f7076">

2024-06-12 14:59 UTC, isabelhb commented
Ik vind upcoming reservations niet echt mooi responsive. 
![afbeelding](https://github.com/76eren/IPSEN5-frontend/assets/117602528/83a162b0-ab38-4f7a-b7a3-f74d4eea03a6)
De rijen staan niet uitgelijnd met de tabelkoppen en rechts uitlijnen van locatie vind ik geen goede keuze.

2024-06-12 15:00 UTC, isabelhb requested changes

2024-06-12 15:00 UTC, isabelhb commented on src/app/reservation-details/reservation-details.component.html
Zie mijn vorige comment

2024-06-12 18:09 UTC, s1143282 commented on src/app/reservation-details/reservation-details.component.html
ik ging het design hiervan nog aanpassen dus daar kijk ik dan wel naar

2024-06-13 07:43 UTC, Yaman-Kwefati approved these changes

2024-06-13 09:17 UTC, isabelhb approved these changes

2024-06-13 09:17 UTC, merged