Feat/favorites in agenda
76eren/IPSEN5-frontend pull request #38
Opened 2024-06-12 16:21 UTC by 76eren

2024-06-12 17:23 UTC, Yaman-Kwefati requested changes

2024-06-12 17:23 UTC, Yaman-Kwefati commented on src/app/calendar/calendar.component.ts
> +                console.log('Reservations of selected user: ', this.events[0]);
kun je die logs verwijderen

2024-06-13 09:03 UTC, isabelhb approved these changes

2024-06-13 09:04 UTC, Yaman-Kwefati approved these changes

2024-06-13 09:05 UTC, merged