Fix/favorites spacing
76eren/IPSEN5-frontend pull request #41
Opened 2024-06-13 09:58 UTC by StanSmits

2024-06-15 11:50 UTC, s1143282 requested changes

2024-06-15 11:50 UTC, s1143282 commented on src/app/home/home.component.ts
> +      console.log(this.user)
console.log weghalen graag

2024-06-17 17:32 UTC, s1143282 approved these changes

2024-06-18 14:34 UTC, Yaman-Kwefati approved these changes

2024-06-18 14:34 UTC, merged