Feat/agenda reservation
76eren/IPSEN5-frontend pull request #43
Opened 2024-06-14 12:40 UTC by isabelhb

Het datatype an events is naar any veranderd, zodat ik een extra property kon toevoegen om te checken bij het klikken of een event van een favoriet is of van de ingelogde user zelf.

2024-06-15 11:54 UTC, s1143282 requested changes

2024-06-15 11:54 UTC, s1143282 commented on src/app/calendar/calendar.component.ts
> +        console.error('Error fetching reservations: ', error);
Kun je een popup maken van deze console.error

2024-06-16 10:45 UTC, 76eren approved these changes

2024-06-16 10:46 UTC, s1143282 approved these changes

2024-06-16 10:46 UTC, merged